### ISSUE TITLE
Swift icon

### ISSUE THREAD

**Issue by HazAT** [getsentry/platformicons#1]
Can you please add a swift icon to the repo?
Thx 👍

**Comment by ckj** [comment]
@HazAT We've decided not to continue work on Platformicons. We've made this change on the marketing pages but not in the app or docs yet. Is there a chance you could make use of the apple logo until we are able to?

**Comment by HazAT** [comment]
I already use the apple icon but since Swift has an own fancy icon I thought it makes sense.
<img width="1121" alt="screen shot 2017-02-27 at 19 45 28" src="https://cloud.githubusercontent.com/assets/363802/23374647/701aa132-fd25-11e6-849d-e4b4f57cfabc.png">
But we can close it then I guess
