### ISSUE TITLE
Update Angular Icon

### ISSUE THREAD

**Issue by Lms24** [getsentry/platformicons#129]
Angular was just rebranded and got a new logo (along with a much needed new [dev docs page](https://angular.dev/)). Let's show the Angular community that we're up to date and update our platform icon.

![image](https://github.com/getsentry/platformicons/assets/8420481/0bf5c5b3-81d5-4166-afab-6666073a2d08)

[New Angular press kit](https://angular.dev/press-kit)

[New Logo files](https://drive.google.com/drive/folders/1IgcAwLDVZUz8ycnFa7T4_H6B4V4LhYUQ)

**Comment by Jesse-Box** [comment]
@Lms24 marking this issue as done!
