### ISSUE TITLE
Missing Spring Boot Logo

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/platformicons#14]
Since couple of days, Spring Boot is on the top level of the Sentry docs (https://docs.sentry.io/) but it's using a Java logo. We should use either Spring or Spring Boot Logo

- Spring - https://spring.io/images/projects/spring-edf462fec682b9d48cf628eaf9e19521.svg
- Spring Boot - https://pbs.twimg.com/profile_images/1235868806079057921/fTL08u_H_400x400.png

Since Spring logo is much better recognized in the community I would lean towards using Spring logo instead of Spring Boot.

**Comment by bruno-garcia** [comment]
@maciejwalkowiak the logo is up, we need to set up now on the docs, and wizard

**Comment by maciejwalkowiak** [comment]
Correct me if I am wrong but I think platformicons have to be released first so that we can use them in docs.
